version: 1.0.{build}
build_script: 
- ps: >-
    $DEPLOY_URL = "https://ci.appveyor.com/api/buildjobs/$Env:APPVEYOR_JOB_ID/artifacts/src%2Fmudlet.zip"
    
    echo "Deployed the output to $DEPLOY_URL"
